import { initializeApp } from 'firebase/app';
import { getFirestore, doc, updateDoc, getDoc } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyDuc8AX8NTfEJHsJP018uG1J3b1PG4KKrQ",
  authDomain: "super-bot-007.firebaseapp.com",
  projectId: "super-bot-007",
  storageBucket: "super-bot-007.firebasestorage.app",
  messagingSenderId: "929685785305",
  appId: "1:929685785305:web:4cbdd1c7b8fcb381e7ccc8"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

const BOT_ID = 'SUPERBOT007-DEMO';

// Video URLs for each service (generated by AI)
const videoURLs = [
  'https://www.genspark.ai/api/files/s/Vx5PWmSw',   // FREE Plan — green robot
  'https://www.genspark.ai/api/files/s/4PTyn1Ge',   // PRO Plan — gold robot
  'https://www.genspark.ai/api/files/s/8PqFiVee',   // Agency — team robots
];

// Hero video for about section
const heroVideoURL = 'https://www.genspark.ai/api/files/s/hZCxagUY';

const ref = doc(db, 'bots', BOT_ID);
const snap = await getDoc(ref);
if(!snap.exists()){ console.log('Bot not found'); process.exit(1); }

const data = snap.data();
const services = data.services || [];

// Update each service with corresponding video
services.forEach((s, i) => {
  if(videoURLs[i]) s.image = videoURLs[i];
});

await updateDoc(ref, { services, heroVideoURL });
console.log('✅ Videos actualizados en Firebase para', BOT_ID);
console.log('Services updated:', services.length);
process.exit(0);
